# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Continous Delivery
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2.0.6
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4.2.2
      - uses: googleapis/release-please-action@v4.2.0
        with:
          release-type: go
          token: ${{ steps.app-token.outputs.token }}
